# Generated by Django 2.0.4 on 2020-05-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caigou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '采购',
            },
        ),
        migrations.CreateModel(
            name='chanpin',
            fields=[
                ('cpcode', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('shuliang', models.IntegerField(verbose_name='工序数量')),
            ],
            options={
                'verbose_name': '产品',
            },
        ),
        migrations.CreateModel(
            name='chanpinBOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cengji', models.IntegerField(verbose_name='层级')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('chanpin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.chanpin', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品BOM',
            },
        ),
        migrations.CreateModel(
            name='chukudan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('work', models.CharField(max_length=128, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '出库单',
            },
        ),
        migrations.CreateModel(
            name='cunenglifenxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('diyitian', models.IntegerField(verbose_name='第一天')),
                ('diertian', models.IntegerField(verbose_name='第二天')),
                ('disantian', models.IntegerField(verbose_name='第三天')),
                ('disitian', models.IntegerField(verbose_name='第四天')),
                ('diwutian', models.IntegerField(verbose_name='第五天')),
                ('diliutian', models.IntegerField(verbose_name='第六天')),
                ('diqitian', models.IntegerField(verbose_name='第七天')),
            ],
            options={
                'verbose_name': '粗能力分析',
            },
        ),
        migrations.CreateModel(
            name='daohuotongzhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caigou', models.CharField(max_length=128, verbose_name='采购单号')),
                ('name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '到货通知',
            },
        ),
        migrations.CreateModel(
            name='dingdan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('kaishi', models.DateField(verbose_name='开始时间')),
                ('jieshu', models.DateField(verbose_name='结束时间')),
                ('chanpin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.chanpin', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='feiliaodan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('work', models.CharField(max_length=128, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '废料单',
            },
        ),
        migrations.CreateModel(
            name='fuhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diyitian', models.IntegerField(default=0, verbose_name='第一天')),
                ('diertian', models.IntegerField(default=0, verbose_name='第二天')),
                ('disantian', models.IntegerField(default=0, verbose_name='第三天')),
                ('disitian', models.IntegerField(default=0, verbose_name='第四天')),
                ('diwutian', models.IntegerField(default=0, verbose_name='第五天')),
                ('diliutian', models.IntegerField(default=0, verbose_name='第六天')),
                ('diqitian', models.IntegerField(default=0, verbose_name='第七天')),
            ],
            options={
                'verbose_name': '工作中心负荷表',
            },
        ),
        migrations.CreateModel(
            name='gongxuzhuanyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=128, verbose_name='转移前派工单')),
                ('name2', models.CharField(max_length=128, verbose_name='转移后派工单')),
            ],
            options={
                'verbose_name': '工序转移',
            },
        ),
        migrations.CreateModel(
            name='gongyiluxian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gongxuhao', models.CharField(max_length=128, verbose_name='工序号')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('time', models.IntegerField(verbose_name='加工时间')),
                ('guanjiangongxu', models.BooleanField(default=False, verbose_name='是否为关键工序')),
                ('chanpin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.chanpin', verbose_name='产品')),
            ],
            options={
                'verbose_name': '工艺路线',
            },
        ),
        migrations.CreateModel(
            name='gongzuozhongxin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='工作中心名称')),
            ],
            options={
                'verbose_name': '工作中心',
            },
        ),
        migrations.CreateModel(
            name='kucun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '库存',
            },
        ),
        migrations.CreateModel(
            name='lingliaodan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='派工单号')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '领料单',
            },
        ),
        migrations.CreateModel(
            name='nenglixuqiufenxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='工作中心')),
                ('diyitian', models.IntegerField(verbose_name='第一天')),
                ('diertian', models.IntegerField(verbose_name='第二天')),
                ('disantian', models.IntegerField(verbose_name='第三天')),
                ('disitian', models.IntegerField(verbose_name='第四天')),
                ('diwutian', models.IntegerField(verbose_name='第五天')),
                ('diliutian', models.IntegerField(verbose_name='第六天')),
                ('diqitian', models.IntegerField(verbose_name='第七天')),
            ],
            options={
                'verbose_name': '能力需求分析',
            },
        ),
        migrations.CreateModel(
            name='paigongdan',
            fields=[
                ('paigongcode', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=128, null=True, verbose_name='工作人员')),
                ('name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('gongzuozhongxin', models.CharField(max_length=128, verbose_name='工作中心')),
                ('kaishi', models.CharField(max_length=128, verbose_name='开始时间')),
                ('jieshu', models.CharField(max_length=128, verbose_name='结束时间')),
                ('jinqian', models.CharField(max_length=128, verbose_name='紧前派工单')),
                ('jinhou', models.CharField(max_length=128, verbose_name='紧后派工单')),
                ('lingliao', models.BooleanField(default=False, verbose_name='领料状态')),
                ('zhijian', models.BooleanField(default=False, verbose_name='质检状态')),
                ('zhuanyi', models.BooleanField(default=False, verbose_name='转移状态')),
                ('dingdan', models.CharField(max_length=128, verbose_name='订单号')),
            ],
            options={
                'verbose_name': '派工单',
            },
        ),
        migrations.CreateModel(
            name='rukudan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('work', models.CharField(max_length=128, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '入库单',
            },
        ),
        migrations.CreateModel(
            name='rukushenqingdan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
                ('work', models.CharField(max_length=128, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '入库申请单',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='物料名字')),
                ('shuliang', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '计算',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='登录名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('work', models.CharField(choices=[('sheji', '设计人员'), ('jihua', '计划人员'), ('caigou', '采购人员'), ('shengchan', '生产人员'), ('zhijian', '质检人员'), ('kucun', '库存人员')], default='', max_length=32, verbose_name='职位')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='wuliao',
            fields=[
                ('wlcode', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='物料名称')),
            ],
            options={
                'verbose_name': '物料',
            },
        ),
        migrations.CreateModel(
            name='wuliaoxuqiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='工序名称')),
                ('diyitian', models.IntegerField(verbose_name='第一天')),
                ('diertian', models.IntegerField(verbose_name='第二天')),
                ('disantian', models.IntegerField(verbose_name='第三天')),
                ('disitian', models.IntegerField(verbose_name='第四天')),
                ('diwutian', models.IntegerField(verbose_name='第五天')),
                ('diliutian', models.IntegerField(verbose_name='第六天')),
                ('diqitian', models.IntegerField(verbose_name='第七天')),
            ],
            options={
                'verbose_name': '物料需求计划',
            },
        ),
        migrations.CreateModel(
            name='zhijiandan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='派工单号')),
                ('hege', models.IntegerField(verbose_name='合格数量')),
                ('buhege', models.IntegerField(verbose_name='不合格数量')),
                ('work', models.CharField(max_length=128, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '质检单',
            },
        ),
        migrations.CreateModel(
            name='zhushengchan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('diyitian', models.IntegerField(verbose_name='第一天')),
                ('diertian', models.IntegerField(verbose_name='第二天')),
                ('disantian', models.IntegerField(verbose_name='第三天')),
                ('disitian', models.IntegerField(verbose_name='第四天')),
                ('diwutian', models.IntegerField(verbose_name='第五天')),
                ('diliutian', models.IntegerField(verbose_name='第六天')),
                ('diqitian', models.IntegerField(verbose_name='第七天')),
                ('cunengli', models.BooleanField(default=False, verbose_name='粗能力分析')),
                ('nenglixuqiu', models.BooleanField(default=False, verbose_name='能力需求分析')),
                ('dingdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.dingdan', verbose_name='订单')),
            ],
            options={
                'verbose_name': '主生产计划',
            },
        ),
        migrations.AddField(
            model_name='wuliaoxuqiu',
            name='chanpin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.zhushengchan', verbose_name='主生产计划'),
        ),
        migrations.AddField(
            model_name='wuliaoxuqiu',
            name='chanpinBOM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.chanpinBOM', verbose_name='产品BOM'),
        ),
        migrations.AddField(
            model_name='nenglixuqiufenxi',
            name='chanpin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.zhushengchan', verbose_name='主生产计划'),
        ),
        migrations.AddField(
            model_name='nenglixuqiufenxi',
            name='gongzuozhongxin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.gongzuozhongxin', verbose_name='工作中心'),
        ),
        migrations.AddField(
            model_name='gongzuozhongxin',
            name='person',
            field=models.ManyToManyField(to='shujuku.User'),
        ),
        migrations.AddField(
            model_name='gongyiluxian',
            name='gongzuozhongxin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.gongzuozhongxin', verbose_name='工作中心'),
        ),
        migrations.AddField(
            model_name='gongyiluxian',
            name='wuliao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.wuliao', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='fuhe',
            name='gongzuozhongxin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.gongzuozhongxin', verbose_name='工作中心'),
        ),
        migrations.AddField(
            model_name='cunenglifenxi',
            name='chanpin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.zhushengchan', verbose_name='主生产计划'),
        ),
        migrations.AddField(
            model_name='cunenglifenxi',
            name='gongzuozhongxin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shujuku.gongzuozhongxin', verbose_name='工作中心'),
        ),
    ]
